function [obs,cfg] = wust_validate_reconstruction(obs,initial,cfg)
obs=wust_validate_measurements(obs);
required={'backend','schedule','bounds_mps','max_update_mps','step_damping', ...
    'source_batch_size','pml_strength','pml_m','stencil_bounds','wavenumber', ...
    'filter_cutoff','filter_order','update_mask'};
allowed=[required,{'dispersion','planned_schedule_length'}];
assert(all(ismember(required,fieldnames(cfg))) && all(ismember(fieldnames(cfg),allowed)), ...
    'WUST:InvalidInput','Missing or unsupported reconstruction config fields');
for name={'pml_m','pml_strength','max_update_mps','step_damping','source_batch_size','filter_order'}
    v=cfg.(name{1});assert(isnumeric(v)&&isreal(v)&&isscalar(v)&&isfinite(v)&&v>0, ...
        'WUST:InvalidInput','Expected positive finite %s',name{1});
end
assert(cfg.source_batch_size==round(cfg.source_batch_size) && cfg.filter_order==round(cfg.filter_order) && ...
    isscalar(cfg.filter_cutoff)&&isfinite(cfg.filter_cutoff)&&cfg.filter_cutoff>=0, ...
    'WUST:InvalidInput','Invalid batch/filter controls');
for name={'bounds_mps','stencil_bounds'}
    b=cfg.(name{1});assert(numel(b)==2&&all(isfinite(b))&&b(1)>0&&b(2)>b(1), ...
        'WUST:InvalidInput','Invalid speed bounds');
end
assert(ismember(string(cfg.backend),["cpu","gpu"])&& ...
    ismember(string(cfg.wavenumber),["continuum","kwave-ldr9"]), ...
    'WUST:InvalidInput','Unsupported backend/wavenumber');
if strcmp(cfg.wavenumber,'kwave-ldr9')
    assert(isfield(cfg,'dispersion'), 'WUST:InvalidInput','LDR9 requires explicit simulation dispersion facts');
end
assert(isequal(size(initial),[numel(obs.y_m),numel(obs.x_m)]) && isreal(initial) && ...
    all(isfinite(initial(:))) && all(initial(:)>=cfg.bounds_mps(1)&initial(:)<=cfg.bounds_mps(2)), ...
    'WUST:InvalidInput','Initial map must match grid and speed bounds; no resize or scalar expansion');
assert(isequal(size(cfg.update_mask),size(initial)) && ...
    all(cfg.update_mask(:)==0|cfg.update_mask(:)==1), 'WUST:InvalidInput','Invalid update mask');
cfg.update_mask=logical(cfg.update_mask);
[X,Y]=meshgrid(obs.x_m,obs.y_m);tol=16*eps(max(abs([obs.x_m(:);obs.y_m(:)]))+1);
interior=X>min(obs.x_m)+cfg.pml_m-tol & X<max(obs.x_m)-cfg.pml_m+tol & ...
    Y>min(obs.y_m)+cfg.pml_m-tol & Y<max(obs.y_m)-cfg.pml_m+tol;
interior([1,end],:)=false;interior(:,[1,end])=false;
assert(all(~cfg.update_mask(:)|interior(:)), 'WUST:InvalidInput','Update mask enters PML/Dirichlet boundary');
s=cfg.schedule;
assert(isnumeric(s)&&isreal(s)&&(isempty(s)||isvector(s))&&all(isfinite(s(:))) && ...
    all(s(:)==round(s(:))&s(:)>=1&s(:)<=numel(obs.frequencies_hz)), ...
    'WUST:InvalidInput','Invalid canonical frequency-index schedule');
if ~isfield(cfg,'planned_schedule_length'),cfg.planned_schedule_length=numel(s);end
p=cfg.planned_schedule_length;
assert(isscalar(p)&&isfinite(p)&&p==round(p)&&p>=numel(s), ...
    'WUST:InvalidInput','planned_schedule_length must cover the supplied schedule');
end
